Kovalenko
nonGratis/retarder-io-23-3 pull request #14
Opened 2024-03-24 15:14 UTC by AlexKovi3

2024-03-24 15:39 UTC, nonGratis requested changes
Також не забувай про пробіли. Також важливо правильно описувати основний сценарій:
суб'єкт -> його дія (теперішній час 3 особа) -> опис

2024-03-24 15:39 UTC, nonGratis commented on docs/requirements/stakeholders-needs.md
> +Простота установки та налаштування системи, щоб користувачі могли швидко почати використовувати її.
плагіат з минулорічної роботи

2024-03-24 15:39 UTC, nonGratis commented on docs/requirements/stakeholders-needs.md
Перше не треба, описане у виключних. Друге скороти. Третє без детального опису кроків в дії. Що за `подібну опцію` якщо не знаєш не пиши, якщо це необхідно то детально. Система може не може, це сценарій, він прописує  доволі точні і зрозумілі послідовності дій. Сьоме можеш прибрати.

2024-03-24 15:39 UTC, nonGratis commented on docs/requirements/stakeholders-needs.md
> +| ***ВИКЛЮЧНІ СИТУАЦІЇ***: | Обмежена кількість прав доступу.                                                                                                   |
Такжо можливе відсутність джерела та відмова адміністратора від видалення

2024-03-24 15:39 UTC, nonGratis commented on docs/requirements/stakeholders-needs.md
> +
Перше і друге об'єднати і скоротити. П'яте і шосте теж саме. Сьоме на видалення, це не стосується цього сценарію

2024-03-24 16:14 UTC, AlexKovi3 commented on docs/requirements/stakeholders-needs.md
> +
Виправив

2024-03-24 16:14 UTC, AlexKovi3 commented on docs/requirements/stakeholders-needs.md
> +| ***ВИКЛЮЧНІ СИТУАЦІЇ***: | Обмежена кількість прав доступу.                                                                                                   |
Додав

2024-03-24 16:14 UTC, AlexKovi3 commented on docs/requirements/stakeholders-needs.md
Прибрав

2024-03-24 16:14 UTC, AlexKovi3 commented on docs/requirements/stakeholders-needs.md
> +Простота установки та налаштування системи, щоб користувачі могли швидко почати використовувати її.
Покращив

2024-03-24 16:18 UTC, nonGratis requested changes
Ще раз:
суб'єкт -> дія (теперішній час 3 особа) -> опис

2024-03-24 16:18 UTC, nonGratis commented on docs/requirements/stakeholders-needs.md
> +Забезпечення безпеки даних та захисту від несанкціонованого доступу до медіа-контенту.
в нас система аналізу, не захисту

2024-03-24 17:01 UTC, nonGratis requested changes

2024-03-24 17:01 UTC, nonGratis commented on docs/requirements/stakeholders-needs.md
> +Система повинна дати змогу працювати з різними форматами медіа-контенту, такими як відео, зображення, аудіо тощо.
Система працює

2024-03-24 17:01 UTC, nonGratis commented on docs/requirements/stakeholders-needs.md
> +| ***ОСНОВНИЙ СЦЕНАРІЙ***: | 1. Адміністратор входить в адміністративний інтерфейс системи за допомогою своїх облікови даних та переходить до відповідного розділу адміністративного інтерфейсу. <br />
В першому пункті описувати, що таке авторизація не треба,  я вже казав про скорочення. Нах це `В адміністративному інтерфейсі`.  Нас це хвилювати це `Після введення всієї необхідної інформації адміністратор перевіриє дані щодо нового джерела та` . Чесно лінь читати останню воду

2024-03-24 17:01 UTC, nonGratis commented on docs/requirements/stakeholders-needs.md
> +| ***ОСНОВНИЙ СЦЕНАРІЙ***: |1.Адміністратор переходить до розділу адміністрування, де розміщені налаштування та опції керування джерелами. <br />2. Адміністратор знаходить в списку джерел те, яке баж
лишнє `, де розміщені налаштування та опції керування джерелами`
Вплані має `Система має попросити?` Вона це робить, це не жива істота. лишнє `, щоб уникнути випадкових втрат даних.`

2024-03-25 04:46 UTC, nonGratis commented on docs/requirements/stakeholders-needs.md
> +| ***ОСНОВНИЙ СЦЕНАРІЙ***: | 1. Адміністратор входить в адміністративний інтерфейс системи за допомогою своїх облікови даних та переходить до відповідного розділу адміністративного інтерфейсу. <br />
Воно якось не ясно написано?

2024-03-26 18:40 UTC, nonGratis approved these changes

2024-03-26 18:40 UTC, nonGratis commented on docs/requirements/stakeholders-needs.md
> +| ***ОСНОВНИЙ СЦЕНАРІЙ***: |1.Адміністратор переходить до розділу адміністрування, де розміщені налаштування та опції керування джерелами. <br />2. Адміністратор знаходить в списку джерел те, яке баж
Теперішній час третього особи

2024-03-26 18:40 UTC, merged